name: "Neuron"
description: "Because I'm sick to death of AppDaemon"
version: "0.0.0"
slug: "neuron"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  packages:
    - jedi_enclave
schema:
  packages:
    - str
  victoria_logs_uri: url?
  victoria_logs_username: str?
  victoria_logs_password: password?
homeassistant_api: true
map:
  - addon_config:rw
  - media:rw
discovery:
  - neuron
